[package]
name = "jsonlrpc_mio"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonlrpc = "0.1.3"
mio = { version = "1.0.2", features = ["os-poll", "net"] }
serde = "1.0.214"
serde_json = "1.0.132"
